services:
  web:
    build: .
    container_name: bookstore-web
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
    working_dir: /var/www/html
    depends_on:
      - db


  db:
    image: mysql:8.0
    container_name: bookstore-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bookstore
      MYSQL_USER: bookstore
      MYSQL_PASSWORD: bookstore
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro

volumes:
  db_data:
